# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateTimeField(verbose_name='date of birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('status', models.CharField(choices=[('A', 'Available'), ('R', 'Reserved'), ('S', 'Sold')], max_length=1)),
                ('picture', models.ImageField(blank=True, upload_to='')),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
