# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalentry',
            name='color',
            field=models.CharField(choices=[('TA', 'Tabby'), ('CP', 'Colorpoint')], default='TA', max_length=2),
        ),
        migrations.AlterField(
            model_name='animalentry',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='animalentry',
            name='status',
            field=models.CharField(choices=[('A', 'Available'), ('R', 'Reserved'), ('S', 'Sold')], default='A', max_length=1),
        ),
    ]
