# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170619_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalentry',
            name='date_of_birth',
            field=models.DateField(verbose_name='date of birth'),
        ),
    ]
