# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170619_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalentry',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
