# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170620_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalentry',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('picture', '100x100', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='animalentry',
            name='picture',
            field=models.ImageField(blank=True, upload_to='media/images/'),
        ),
    ]
