# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 20:01
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170622_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalentry',
            name='cropped_picture',
        ),
        migrations.AlterField(
            model_name='animalentry',
            name='picture',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
